### PR TITLE
Add honey to metamask

### PR DESCRIPTION
**Pull request by famole**
PR for adding the button "Add token to metamask" approved in the following proposal https://forum.1hive.org/t/add-hny-to-your-wallet-button-on-ui/1093.

Screen Shot 2020-12-04 at 7 02 03 PM

### CODE REVIEW

**Comment by phoenixdaveth** [comment]
I think we need to change add button to light grey

**Comment by onbjerg** [comment]
I agree with David

**Comment by famole** [comment]
Hey guys, actually the button is like this: 
Screen Shot 2020-12-16 at 2 34 38 PM

The green color is "onhover".
Let me know if looks okay

**Comment by phoenixdaveth** [comment]
its looking good.

**Comment by onbjerg** [comment]
Thanks 🎇

**Pull request merged**
